### PR TITLE
v0 Dart client generation

### PR DESCRIPTION
**Pull request by austinmilt**
This PR adds Dart client code generation. It requires a single import into the client's codebase (documented in the README)

This version includes

- [x] client code generation (see base directory starting in `main.go.tmpl`)
- [x] services interface generation for mocking in tests (`types.go.tmpl`)
- [x] test validation against the test webrpc schema (`tests/scripts/test.sh` and `tests/test/reference_test.dart`)
- [x] test validation against an additional webrpc schema (`tests/test/custom_test.dart`)
- [x] CI test automation (`.github/workflows/ci.yml`)
- [x] an example Flutter client app with a Go backend (`_examples/flutter-go/`)

Note this version ignores wide/large number truncation that occurs in web environments (i.e. Flutter web) (see https://github.com/webrpc/webrpc/issues/283)

### CODE REVIEW

**Comment by austinmilt** [comment]
@VojtechVitek looking for reviews at your leisure

**Review by VojtechVitek — APPROVED** [review]
LGTM. I think this is excellent!

@austinmilt What a great contribution to the webrpc project. Thank you! 🎉

If you agree, I can get this into webrpc binary as an officially supported client.

I've never worked with Dart, so I won't be able to run/test this myself today.. but the tests suite looks very robust 👍 

Screen Shot 2024-04-25 at 5 51 18 PM

**Comment by austinmilt** [comment]
> LGTM. I think this is excellent!
> 
> @austinmilt What a great contribution to the webrpc project. Thank you! 🎉
> 
> If you agree, I can get this into webrpc binary as an officially supported client.
> 
> I've never worked with Dart, so I won't be able to run/test this myself today.. but the tests suite looks very robust 👍
> 
> Screen Shot 2024-04-25 at 5 51 18 PM

I would love to see this officially supported. Just FYI this version is what I'd consider a minimal implementation

- doesnt support metadata generally
- types cant be compared for deep equality
- doesnt attempt to define or return default values

**Comment by VojtechVitek** [comment]
@austinmilt it's a very great start :) Feel free to create issues for what you think is missing 👍

**Comment by austinmilt** [comment]
I made some issues but will likely wait to implement anything until/unless folks end up using the library (including myself :D) .

**Pull request merged**
